export const HEBREW = {
  appName: 'FuelApp - מעקב תדלוק',
  login: {
    title: 'התחברות',
    username: 'שם משתמש',
    password: 'סיסמה',
    submit: 'התחברות',
    error: 'שם משתמש או סיסמה שגויים',
  },
  vehicles: {
    title: 'רשימת רכבים',
    search: 'חיפוש לפי מספר רכב...',
    vehicleNumber: 'מספר רכב',
    vehicleType: 'סוג רכב',
    lastOdometer: 'ק״מ אחרון',
    distanceSinceRefuel: 'ק״מ מאז תדלוק',
    estimatedFuelStatus: 'סטטוס דלק משוער',
    estimatedRange: 'טווח נסיעה משוער',
    actionStatus: 'סטטוס פעולה',
    lastUpdated: 'עודכן לאחרונה',
    addVehicle: 'הוספת רכב',
    noVehicles: 'אין עדיין רכבים במערכת',
    nickname: 'כינוי',
    notes: 'הערות',
  },
  vehicleDetails: {
    scanOdometer: 'סריקת ק״מ',
    manualEntry: 'הזן ידנית',
    markFullRefuel: 'סומן תדלוק מלא',
    recentHistory: 'היסטוריית עדכונים',
    noOdometer: 'עדיין לא הוזן ק״מ לרכב זה',
    noBaseline: 'יש לסמן תדלוק מלא ראשון כדי להתחיל לחשב סטטוס דלק משוער',
    basedOn: 'מבוסס על ק״מ מאז תדלוק מלא אחרון',
    km: 'ק״מ',
    estimatedRemaining: 'טווח משוער שנותר',
  },
  odometer: {
    enterValue: 'הזנת קריאת ק״מ',
    currentOdometer: 'ק״מ נוכחי',
    newReading: 'קריאה חדשה',
    save: 'שמירה',
    cancel: 'ביטול',
    confirm: 'אישור',
    invalidNumber: 'יש להזין מספר ק״מ תקין',
    lowerThanCurrent: 'לא ניתן להזין ק״מ נמוך מהקריאה האחרונה',
  },
  refuel: {
    confirmTitle: 'אישור תדלוק מלא',
    confirmMessage: 'האם לסמן תדלוק מלא? הקריאה הנוכחית תהפוך לבסיס החישוב החדש.',
    confirm: 'אישור תדלוק',
    cancel: 'ביטול',
    noOdometerError: 'לא ניתן לסמן תדלוק לפני הזנת ק״מ עדכני',
  },
  scan: {
    title: 'סריקת מד ק״מ',
    capture: 'צלם',
    retry: 'נסה שוב',
    processing: 'מעבד...',
    switchToManual: 'עבור להזנה ידנית',
    suggestedValue: 'ערך מזוהה',
    editAndConfirm: 'ניתן לערוך לפני אישור',
  },
  admin: {
    title: 'ניהול',
    vehicleManagement: 'ניהול רכבים',
    vehicleTypeSettings: 'הגדרות סוג רכב',
    createVehicle: 'יצירת רכב חדש',
    editVehicle: 'עריכת רכב',
    fuelTankCapacity: 'נפח מיכל (ליטר)',
    kmPerLiter: 'ק״מ לליטר (משוער)',
    thresholds: 'סיפי התראה',
    save: 'שמירה',
  },
  common: {
    loading: 'טוען...',
    error: 'שגיאה',
    back: 'חזרה',
    logout: 'התנתקות',
  },
} as const;
